### ISSUE TITLE
Question: Update queries

### ISSUE THREAD

**Issue by dominicfarr** [Reggino/SdbNavigator#17]
Does SdbNavigator support update queries? 

I can see it has inline updates, but I would like to update via the Run query interface to effect more than one row.

`update 'table' set 'colum' = 'value' where 'column' = 'value'`

**Comment by Reggino** [comment]
SdbNavigator is a straight-forward interface for SimpleDB and SimpleDB doesn't support ```update``` queries as far as i know.

Updating is done via another method as described here: http://docs.aws.amazon.com/AmazonSimpleDB/latest/DeveloperGuide/ConditionalPut.html
