### ISSUE TITLE
Support for session tokens

### ISSUE THREAD

**Issue by agianni** [Reggino/SdbNavigator#18]
Hello,
My company uses AWS Security Token Service (STS) and my temporary credentials have this format.
aws_access_key_id
aws_secret_access_key
aws_session_token

SdbNavigator is saying AWS Access Key ID does not exist when I just pass the ak/sk pair without the token.
I am new to Amazon and trying to understand if the STS credential is not usable without the token (and extra handling that goes along with it) or if the session token is optional when a tool like this does not accept it.
Thanks 
Antonoio

**Comment by andrewsolomon** [comment]
Hi Antonoio

Just to check the simplest issue first - are you selecting the region where the access key pair is based?

Andrew

**Comment by agianni** [comment]
Yes I am, I am using US-East.  After I brought my issue to AWS Tech Support I got this reply.
You cannot use an STS token without all 3 parts (access key, secret key, session token) - when you try you get errors just like what you're seeing.

**Comment by agianni** [comment]
You can find the list of AWS services that support STS tokens here: 
http://docs.aws.amazon.com/STS/latest/UsingSTS/UsingTokens.html
SimpleDB is on the list, but I suspect that the SimpleDB navigator plugin you're using is 3rd party, in which case it may or may not support them.

**Comment by agianni** [comment]
![sdb](https://cloud.githubusercontent.com/assets/13908750/9422394/223b2b10-4860-11e5-9286-1850f25cc863.GIF)

**Comment by Reggino** [comment]
Indeed SdbNavigator does not yet support STS, since that requires a slightly different way to [http://docs.aws.amazon.com/STS/latest/UsingSTS/UsingTokens.html ]("sign" te requests).

**Comment by Reggino** [comment]
This has been implemented by @pmdumuid .

A new version (2.0.8) has just been published.
