### ISSUE TITLE
Newlines in attribute values

### ISSUE THREAD

**Issue by jakobcornell** [Reggino/SdbNavigator#19]
Amazon SimpleDB allows newlines in string attribute values. SdbNavigator fetches values with newlines correctly, but since the value is inlined directly in a `div`, newlines show up as spaces, and since single-line `input` elements are used for editing, newlines are stripped while editing.

I'd suggest inlining values in a `pre` element for display and using `textarea`s for editing.

**Comment by Reggino** [comment]
The interface may become a bit messy when every row has its own height. And the textarea-control (with scrollbars) may not fit properly into the grid-cell for editing.

I'ld be happy to review a PR, or I'll try to look into it and experiment a bit when i find the time.

**Comment by jakobcornell** [comment]
Fair concern. I'll likewise look into preparing a PR when I get a chance.
