### ISSUE TITLE
STS fails when role profile require MFA authentication

### ISSUE THREAD

**Issue by sellers** [Reggino/SdbNavigator#22]
As a user I can STS assume role with MFA enabled auth for the AssumedRole so that I can still browser the SDB tables as the assumed role I have taken. 

 Placing the STS credentials in the UI also does not work as it can not find a User with those credentials (as it is a Role I presume)

**Comment by Reggino** [comment]
@sellers To be honest, i do not have any experience with STS. Would it be possible for you to set up a temporary account with limited access to some dummy data? (I'm not even sure it works that way(?))

If you'd send me a PM with the credentials, i'd be able to reproduce the login-issues and i'd be willing to give it a try and look into that. 

Thanks.
