### ISSUE TITLE
SdbNavigator

### ISSUE THREAD

**Issue by Jacek2020** [Reggino/SdbNavigator#26]
Hi,

I am impressed with your product "SdbNavigator,
I have created domein for Simple DB using my credetials,
and I have tried connect to it using SdbNavigator, 
the region of my bucket is:  EU (Frankfurt) eu-central-1

in the drop list of SdbNavigator there is no such a region to choose,
so I can't connect to my domein,

May I ask, if it is possible to choose my region (EU (Frankfurt) eu-central-1) in SdbNavigator

Best Regards,

Jacek.

**Comment by Reggino** [comment]
Hi @Jacek2020,

I've doublechecked [https://docs.aws.amazon.com/general/latest/gr/sdb.html](the documentation) but i don't think SimpleDB is available in Frankfurt. Only Ireland is listed as a possible SDB host...

If you think this is incorrect, please let me know, thnx

**Comment by Jacek2020** [comment]
Hi Tim,

I swear that SimpleDB service works in EU (Frankfurt) eu-central-1,
I attach a sreenshot from my test application in Android,

On this screen a big font on the List it is a name of object (in fact it is photo) I store in Simple Storage Service (S3),
A small font on the List is a name of unique index (IDs) of the row in my SimpleDB table (domain), where I store the name of object in S3,
All of this is only for test purpose, but of course I try my best to create a small apps with more sense,

Judging from the documentation you are right,
But it works also in  EU (Frankfurt) eu-central-1, where I have my the only one bucket,

I don’t know why ☺
May be the documentation is out-of-date,
May be the Amazon add in this region without informing anybody,
Who knows what future holds in their store in terms of Amazon SimpleDb ? ☺

I found your app and thought, it would be a perfect tool to test my data on SimpleDB,
That is a reason of my mailing to you, ☺

Best regards,
Jacek Nowiński
[GDDKIA_ZNAK_2_2_CMYK]
