### ISSUE TITLE
SDBNavigator violates Chrome WebStore terms

### ISSUE THREAD

**Issue by sellers** [Reggino/SdbNavigator#32]
This extension violates the Chrome Web Store policy.

**Comment by Reggino** [comment]
I got a message from Google stating:

"Extension is requesting cookies permission which is not used in the code and tabs are not required for the properties.'

I tried to explain that cookies were used to remember the AWS access key & secret, but that didn't stop the removal from the Webstore....

There is a new version "waiting for approval" without cookies-support, but it all takes some time for some reason....

**Comment by Reggino** [comment]
A new version is released. The item can be installed from the web store as it was before.
